sonata_media:
    class:
        media:             Portal\Bundle\AppBundle\Entity\Media\Media
        gallery:           Portal\Bundle\AppBundle\Entity\Media\Gallery
        gallery_has_media: Portal\Bundle\AppBundle\Entity\Media\GalleryHasMedia
        category:          Portal\Bundle\AppBundle\Entity\Classification\Category

    db_driver:       doctrine_orm
    default_context: default

    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~
