sonata_page:
    class:
         block:      Portal\Bundle\AppBundle\Entity\Page\Block
         page:       Portal\Bundle\AppBundle\Entity\Page\Page
         site:       Portal\Bundle\AppBundle\Entity\Page\Site
         snapshot:   Portal\Bundle\AppBundle\Entity\Page\Snapshot

    multisite: host
    use_streamed_response: false
    slugify_service: sonata.core.slugify.cocur

    ignore_route_patterns:
         - ^(.*)
         - ^liip(.*)
         - ^_wdt(.*)
         - ^_profiler(.*)

    default_template: default

    # Generates a snapshot when a page is saved (from the admin)
    direct_publication: %kernel.debug%

    templates:
        default:  { path: 'SonataPageBundle::layout.html.twig',          name: 'default' }
        2columns: { path: 'SonataPageBundle::2columns_layout.html.twig', name: '2 columns layout' }

    page_defaults:
        homepage: { decorate: false, enabled: true }

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataPageBundle: ~