sonata_admin:
    title: Portal

    templates:
        layout: PortalAppBundle::standard_layout.html.twig

    admin_services:
        portal.github.admin.tag:
            templates:
                form: ['PortalGithubBundle:Form:form_admin_fields.html.twig']

    dashboard:
        groups:
            portal.admin.group.money:
                label: Money
                icon:  '<i class="fa fa-money"></i>'
                items:
                    - route: money_app
                      label: Money

            portal.admin.group.github:
                label: Github
                icon:   '<i class="fa fa-github"></i>'
                items:
                    - portal.github.admin.gist
                    - portal.github.admin.tag

            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context

            sonata.admin.group.site_builder:
                label:           Site Builder
                label_catalogue: SonataPageBundle
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.site

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

    assets:
        stylesheets:
            - assetic/sonata_admin_css.css
            - assetic/sonata_formatter_css.css
            - assetic/sonata_jqueryui_css.css
            - assetic/portal_css.css

        javascripts:
            - assetic/sonata_admin_js.js
            - assetic/sonata_jqueryui_js.js
            - assetic/sonata_formatter_js.js
            - assetic/portal_js.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
